// Global list of models

MODEL(BAMBOO2,                           "models/bamboo2.iqm");
MODEL(VINE,                              "models/vine.iqm");
MODEL(VINE_BROKEN,                       "models/vine_broken.iqm");
MODEL(SWORD,                             "models/sword.iqm");
MODEL(CHECKPOINT,                        "models/checkpoint.iqm");
MODEL(MUSHROOM,                          "models/mushroom.iqm");
MODEL(MUSHROOM2,                         "models/mushroom2.iqm");
MODEL(PLAYER,                            "models/player.iqm");
MODEL(SWORD_EQUIP,                       "models/sword_equip.iqm");
MODEL(HEART,                             "models/heart.iqm");
MODEL(FEATHER,                           "models/feather.iqm");
