#include "ogre.qc"
#include "fiend.qc"
#include "shambler.qc"
#include "knight.qc"
#include "grunt.qc"
#include "scrag.qc"
#include "rottweiler.qc"
#include "zombie.qc"
#include "chthon.qc"

#include "spawn.qc"			// registered
#include "hellknight.qc"	// registered
#include "rotfish.qc"		// registered
#include "vore.qc"			// registered
#include "enforcer.qc"		// registered
#include "shub.qc"			// registered
