#include "_all.qh"

#include "csqcmodel_hooks.qc" // needs to be done early

//#include <lib/csqcmodel/cl_player.qc>

#include "main.qc"
#include "view.qc"
#include "crosshair.qc"
#include "sbar.qc"
#include "shop.qc"
#include "centerprint.qc"

#include "../common/_all.inc"

#include <lib/csqcmodel/cl_model.qc>
#include "../common/physics.qh"
#include <lib/csqcmodel/cl_player.qc>
#include <lib/csqcmodel/interpolate.qc>
